### PR TITLE
feat: add timeout support tcp

### PR DESCRIPTION
**Pull request by Lenny4**
Pull request for: https://github.com/AllInOneYT/react-native-thermal-printer/issues/19

~~Didn't test yet because of: https://github.com/AllInOneYT/react-native-thermal-printer/issues/20~~

~~Waiting for https://github.com/AllInOneYT/react-native-thermal-printer/pull/27 to test~~

Work nice.

No break change.

Need to merge https://github.com/AllInOneYT/react-native-thermal-printer/pull/27 first.

### CODE REVIEW

**Review by AllInOneYT — CHANGES_REQUESTED** [review]
LGTM. Could you please change the default timeout to 1 minute so people from previous version don't experience any changes? From my experience, it sometimes take more than 10 seconds at cold start. Thank you :)

**Comment by AllInOneYT** [comment]
> LGTM. Could you please change the default timeout to 1 minute so people from previous version don't experience any changes? From my experience, it sometimes take more than 10 seconds at cold start. Thank you :)

I mean 30 seconds. same as the default

**Comment by AllInOneYT** [comment]
Are you sure it is in milliseconds? [constructor](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/tree/3.0.1#constructor--tcpconnectionstring-address-int-port-int-timeout)

**Comment by Lenny4** [comment]
Hi @AllInOneYT ,

> I mean 30 seconds. same as the default

I have changed the default waiting time to 30s.

> Are you sure it is in milliseconds? [constructor](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/tree/3.0.1#constructor--tcpconnectionstring-address-int-port-int-timeout)

I though it was in second first but it is in millisecond. I made another test with a valid ip `192.168.1.42` and not valid `192.168.1.41` each time by changing timeout with this code:
```typescript
const testPrint = React.useCallback(async () => {
  const start = new Date().getTime();
  try {
    setResult('');
    await ThermalPrinter.printTcp({
      ip: ip,
      port: parseInt(port, 10),
      payload:
        "[C]<u><font size='big'>" +
        'Test success !' +
        '</font></u>\n' +
        '[L] \n' +
        '[L] \n',
      timeout: parseInt(timeout, 10),
    });
    setResult(
      'Success ! in ' + (new Date().getTime() - start) + ' milliseconds'
    );
  } catch (e) {
    setResult(
      'Failed ! in ' + (new Date().getTime() - start) + ' milliseconds'
    );
  }
}, [timeout, ip, port]);
```
Here the result:
Screenshot from 2022-02-02 18-53-07
Screenshot from 2022-02-02 18-53-55
Screenshot from 2022-02-02 18-54-11

**Comment by Lenny4** [comment]
I have a question, once this feature is merged to you plan to create a release despite https://github.com/AllInOneYT/react-native-thermal-printer/issues/24 ?

**Comment by AllInOneYT** [comment]
Wow, thank you very much for your help :)

**Comment by AllInOneYT** [comment]
> I have a question, once this feature is merged to you plan to create a release despite #24 ?

Sure :)

**Review by AllInOneYT — APPROVED** [review]
LGTM :)

**Pull request merged**
