### PR TITLE
feat: updated bluetooth

### PR DESCRIPTION
**Pull request by amalpsojan**
Bluetooth printing can now target specific mac addresses. Also you can list paired devices by calling `getBluetoothDeviceList()`

### CODE REVIEW

**Comment by amalpsojan** [comment]
> @amalpsojan Thank you again for sharing your hard work. I saw you had done a wonderful job here. Just wondering, have you tested it with real device?

Currently, I have no Thermal printer... But I tested with the same the emulator. Could you please test it with a real device.

> Could you please exclude the `yarn.lock` file from pull request? Thank you 😊

ofcourse... currently I am a little busy... i will do it soon

**Comment by AllInOneYT** [comment]
> > @amalpsojan Thank you again for sharing your hard work. I saw you had done a wonderful job here. Just wondering, have you tested it with real device?
> 
> Currently, I have no Thermal printer... But I tested with the same the emulator. Could you please test it with a real device.
> 
I can confirm that it is working, tested it on real device today :)

**Comment by AllInOneYT** [comment]
#22

**Comment by JelouSoft** [comment]
Hey, it is not working on my environment. 

await ThermalPrinterModule.getBluetoothDeviceList(); don't response anything.

SDK 33

<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.BLUETOOTH"
                     android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"
                     android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />


Thanks for response.

**Pull request closed without merging**
